### ISSUE TITLE
[Bug] The CMake script for protobuf cannot automatically include google/protobuf/any.proto.

### ISSUE THREAD

**Issue by livestronglxr** [AimRT/AimRT#98]
- 环境： windows11 
- 环境变量中已经设置了AimRT的install目录
- 用户工程以三方库的形式引入AimRT
- 但cmake脚本似乎调用的...\fetch_source\protobuf-build\protoc.exe ,从而导致找不到any.proto

---

- Environment: Windows 11
- The AimRT install directory is set in the environment variables.
- The user project includes AimRT as a third-party library.
- However, the CMake script seems to call ...fetch_source\protobuf-build\protoc.exe, which results in any.proto not being found.

**Comment by zhangyi1357** [comment]
这是因为我们使用生成 protobuf 代码的 cmake 脚本中没有包含 protobuf 本身的目录，我已经提交了一个修复此问题的 PR。

作为暂时性的 workaround，你可以在相应 cmake 函数的 OPTIONS 参数提交一个类似的目录，如下所示：

```cmake
add_protobuf_gencode_target_for_proto_path(
  TARGET_NAME ${CUR_TARGET_NAME}_pb_gencode
  PROTO_PATH ${CMAKE_CURRENT_SOURCE_DIR}
  GENCODE_PATH ${CMAKE_CURRENT_BINARY_DIR}
  OPTIONS "--proto_path=${protobuf_SOURCE_DIR}/src")
```

---

This is because the directory of protobuf itself is not included in the cmake script that generates protobuf code. I have submitted a PR to fix this.

As a temporary workaround, you can submit a similar directory in the OPTIONS parameter of the corresponding cmake function, as shown below:

```cmake
add_protobuf_gencode_target_for_proto_path(
  TARGET_NAME ${CUR_TARGET_NAME}_pb_gencode
  PROTO_PATH ${CMAKE_CURRENT_SOURCE_DIR}
  GENCODE_PATH ${CMAKE_CURRENT_BINARY_DIR}
  OPTIONS '--proto_path=${protobuf_SOURCE_DIR}/src')
```

**Comment by livestronglxr** [comment]
响应好迅速！ 智元前途无限！

**Comment by livestronglxr** [comment]
响应好迅速！ 智元前途无限！
